overrideFuncions = false
monitorMode = false
monitor = nil
sizeX, sizeY = term.getSize()
isLowSpace = false
DEFAULT_BACKGROUND_COLOR = 1
backgroundColor = DEFAULT_BACKGROUND_COLOR
DEFAULT_UI_COLOR_1 = 256
uiColor1 = DEFAULT_UI_COLOR_1
DEFAULT_UI_COLOR_2 = 128
uiColor2 = DEFAULT_UI_COLOR_2
wifiOn = false
soundOn = false
user = "xXDMOGXx"
colorMap = {}
textMap = {}
functionMap = {}
overrideFunctionMap = {}
imageMap = {}
paintMap = {}
assetDict = {}
varDict = {}

appExt = ".app"
prgExt = "PRG.lua"
mapExt = ".map"
setExt = ".set"
picExt = ".cpic"